// WBS/export/figma-replica/vue/src/views/mbuttercup-pdpa.vue
<template>
  <div class="mbuttercup-pdpa-container">
    <div class="mbuttercup-pdpa-mbuttercup-pdpa">
      <div class="mbuttercup-pdpa-imageand-price">
        <div class="mbuttercup-pdpa-image">
          <button class="mbuttercup-pdpa-button-favorite">
            <img
              alt="IconFavoriteI327"
              src="/external/iconfavoritei327-hrf.svg"
              class="mbuttercup-pdpa-icon-favorite"
            />
          </button>
          <img
            alt="Image13271"
            src="/external/image13271-n2gp-400w.png"
            class="mbuttercup-pdpa-image1"
          />
        </div>
        <div class="mbuttercup-pdpa-frame15135">
          <div class="mbuttercup-pdpa-frame15162">
            <span class="mbuttercup-pdpa-text"><span>Iris Reticulata</span></span>
            <div class="mbuttercup-pdpa-frame15217">
              <button class="mbuttercup-pdpa-dbutton-dot">
                <img
                  alt="IconSCaretI327"
                  src="/external/iconscareti327-y0u3.svg"
                  class="mbuttercup-pdpa-icon-scaret"
                />
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="mbuttercup-pdpa-mprimary-nav">
        <div class="mbuttercup-pdpa-icon-hamburger">
          <img
            alt="HamburgerI327"
            src="/external/hamburgeri327-i0l.svg"
            class="mbuttercup-pdpa-hamburger"
          />
        </div>
        <img
          alt="LogoWordmarkI327"
          src="/external/logowordmarki327-6wnw.svg"
          class="mbuttercup-pdpa-logo-wordmark"
        />
        <div class="mbuttercup-pdpa-icon-basket">
          <img
            alt="UnionI327"
            src="/external/unioni327-mxg.svg"
            class="mbuttercup-pdpa-union"
          />
        </div>
      </div>
      <div class="mbuttercup-pdpa-frame15161">
        <div class="mbuttercup-pdpa-frame15218">
          <div class="mbuttercup-pdpa-mqty-stepper">
            <div class="mbuttercup-pdpa-qty-selector">
              <span class="mbuttercup-pdpa-text2 📱HandheldBodyLargeDefault">
                1
              </span>
            </div>
            <div class="mbuttercup-pdpa-frame15160">
              <div class="mbuttercup-pdpa-qty-selector1">
                <div class="mbuttercup-pdpa-icon-minus">
                  <img
                    alt="PlusI327"
                    src="/external/plusi327-9ix.svg"
                    class="mbuttercup-pdpa-plus"
                  />
                </div>
              </div>
              <div class="mbuttercup-pdpa-qty-selector2">
                <div class="mbuttercup-pdpa-icon-plus">
                  <img
                    alt="PlusI327"
                    src="/external/plusi327-qm3x.svg"
                    class="mbuttercup-pdpa-plus1"
                  />
                </div>
              </div>
            </div>
          </div>
          <span class="mbuttercup-pdpa-text3 📱HandheldBodyLargeBold">
            <span>$1.99/ea</span>
          </span>
        </div>
        <button class="mbuttercup-pdpa-mbutton-pill">
          <span class="mbuttercup-pdpa-text5 📱HandheldBodyLargeDefault">
            <span>Add to basket</span>
          </span>
          <div class="mbuttercup-pdpa-icon-basket1">
            <img
              alt="UnionI327"
              src="/external/unioni327-h23l.svg"
              class="mbuttercup-pdpa-union1"
            />
          </div>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MButtercupPDPA',
  metaInfo: {
    title: 'exported project',
  },
}
</script>

<style scoped>
.mbuttercup-pdpa-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
}
.mbuttercup-pdpa-mbuttercup-pdpa {
  width: 100%;
  height: 698px;
  display: flex;
  overflow: hidden;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
  border-radius: 36px;
  background-color: var(--dl-color-worldpeas_lavender-base);
}
.mbuttercup-pdpa-imageand-price {
  gap: 16px;
  top: 80px;
  left: 24px;
  width: 327px;
  display: flex;
  position: absolute;
  align-items: flex-start;
  flex-shrink: 0;
  flex-direction: column;
}
.mbuttercup-pdpa-image {
  width: 327px;
  height: 372px;
  display: flex;
  overflow: hidden;
  position: relative;
  align-self: stretch;
  align-items: flex-start;
  border-radius: 12px;
}
.mbuttercup-pdpa-button-favorite {
  top: 12px;
  left: 315px;
  width: 36px;
  height: 36px;
  display: flex;
  position: absolute;
  align-items: flex-start;
  flex-shrink: 0;
  border-radius: 100px;
  background-color: var(--dl-color-worldpeas_cremini-base);
}
.mbuttercup-pdpa-icon-favorite {
  top: 9.5px;
  left: 28px;
  width: 20px;
  height: 20px;
  position: absolute;
}
.mbuttercup-pdpa-image1 {
  top: 0px;
  left: 0px;
  width: 327px;
  height: 372px;
  position: absolute;
}
.mbuttercup-pdpa-frame15135 {
  display: flex;
  align-self: stretch;
  align-items: flex-start;
  flex-direction: column;
}
.mbuttercup-pdpa-frame15162 {
  gap: 8px;
  display: flex;
  align-self: stretch;
  align-items: center;
  flex-shrink: 0;
  justify-content: space-between;
}
.mbuttercup-pdpa-text {
  color: var(--dl-color-worldpeas_compost-base);
  height: auto;
  font-size: 48px;
  font-style: Regular;
  text-align: left;
  font-family: Anton;
  font-weight: 400;
  line-height: 120.00000476837158%;
  font-stretch: normal;
  text-decoration: none;
}
.mbuttercup-pdpa-frame15217 {
  gap: 10px;
  display: flex;
  padding: 0 0 4px;
  align-items: flex-start;
}
.mbuttercup-pdpa-dbutton-dot {
  width: 36px;
  height: 36px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
  border-color: rgba(0, 0, 0, 1);
  border-style: solid;
  border-width: 1px;
  border-radius: 100px;
}
.mbuttercup-pdpa-icon-scaret {
  top: 8px;
  left: 28px;
  width: 20px;
  height: 20px;
  position: absolute;
}
.mbuttercup-pdpa-mprimary-nav {
  gap: 71px;
  top: 0px;
  left: 0px;
  width: 375px;
  height: 64px;
  display: flex;
  padding: 14px 24px;
  overflow: hidden;
  position: absolute;
  align-items: center;
  flex-shrink: 0;
  justify-content: space-between;
}
.mbuttercup-pdpa-icon-hamburger {
  width: 20px;
  height: 20px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
}
.mbuttercup-pdpa-hamburger {
  top: 6px;
  left: 1px;
  width: 18px;
  height: 8px;
  position: absolute;
}
.mbuttercup-pdpa-logo-wordmark {
  width: 120px;
  height: 20px;
}
.mbuttercup-pdpa-icon-basket {
  width: 20px;
  height: 20px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
}
.mbuttercup-pdpa-union {
  top: 1px;
  left: 1px;
  width: 18px;
  height: 18px;
  position: absolute;
}
.mbuttercup-pdpa-frame15161 {
  gap: 16px;
  top: 578px;
  left: 24px;
  width: 327px;
  display: flex;
  position: absolute;
  align-items: flex-start;
  flex-shrink: 0;
  flex-direction: column;
}
.mbuttercup-pdpa-frame15218 {
  gap: 8px;
  display: flex;
  align-self: stretch;
  align-items: center;
  flex-shrink: 0;
  justify-content: space-between;
}
.mbuttercup-pdpa-mqty-stepper {
  gap: 12px;
  display: flex;
  overflow: hidden;
  align-items: center;
}
.mbuttercup-pdpa-qty-selector {
  gap: 8px;
  width: 58px;
  height: 32px;
  display: flex;
  padding: 0 8px;
  align-items: center;
  flex-shrink: 0;
  border-color: rgba(0, 0, 0, 1);
  border-style: solid;
  border-width: 1px;
  border-radius: 16px;
  justify-content: center;
}
.mbuttercup-pdpa-text2 {
  color: var(--dl-color-worldpeas_compost-base);
  height: auto;
  flex-grow: 1;
  text-align: center;
  line-height: 160.0000023841858%;
}
.mbuttercup-pdpa-frame15160 {
  gap: 8px;
  display: flex;
  align-items: flex-start;
}
.mbuttercup-pdpa-qty-selector1 {
  gap: 8px;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  flex-shrink: 0;
  border-color: rgba(0, 0, 0, 1);
  border-style: solid;
  border-width: 1px;
  border-radius: 16px;
  justify-content: center;
}
.mbuttercup-pdpa-icon-minus {
  width: 20px;
  height: 20px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
}
.mbuttercup-pdpa-plus {
  top: 9.5px;
  left: 6px;
  width: 8px;
  height: 1px;
  position: absolute;
}
.mbuttercup-pdpa-qty-selector2 {
  gap: 8px;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  flex-shrink: 0;
  border-color: rgba(0, 0, 0, 1);
  border-style: solid;
  border-width: 1px;
  border-radius: 16px;
  justify-content: center;
}
.mbuttercup-pdpa-icon-plus {
  width: 20px;
  height: 20px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
}
.mbuttercup-pdpa-plus1 {
  top: 6px;
  left: 6px;
  width: 8px;
  height: 8px;
  position: absolute;
}
.mbuttercup-pdpa-text3 {
  color: var(--dl-color-worldpeas_compost-base);
  height: auto;
  text-align: left;
  line-height: 160.0000023841858%;
}
.mbuttercup-pdpa-mbutton-pill {
  gap: 8px;
  display: flex;
  padding: 12px 24px;
  align-self: stretch;
  align-items: center;
  flex-shrink: 0;
  border-radius: 12px;
  justify-content: space-between;
  background-color: rgba(114, 1, 168, 1);
}
.mbuttercup-pdpa-text5 {
  color: var(--dl-color-worldpeas_cremini-base);
  height: auto;
  text-align: left;
  line-height: 160.0000023841858%;
}
.mbuttercup-pdpa-icon-basket1 {
  width: 20px;
  height: 20px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-shrink: 0;
}
.mbuttercup-pdpa-union1 {
  top: 1px;
  left: 1px;
  width: 18px;
  height: 18px;
  position: absolute;
}
</style>

// WBS/export/figma-replica/react/src/views/mbuttercup-pdpa.js
import React from 'react'

import { Helmet } from 'react-helmet'

import './mbuttercup-pdpa.css'

const MButtercupPDPA = (props) => {
  return (
    <div className="mbuttercup-pdpa-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="mbuttercup-pdpa-mbuttercup-pdpa">
        <div className="mbuttercup-pdpa-imageand-price">
          <div className="mbuttercup-pdpa-image">
            <button className="mbuttercup-pdpa-button-favorite">
              <img
                alt="IconFavoriteI327"
                src="/external/iconfavoritei327-hrf.svg"
                className="mbuttercup-pdpa-icon-favorite"
              />
            </button>
            <img
              alt="Image13271"
              src="/external/image13271-n2gp-400w.png"
              className="mbuttercup-pdpa-image1"
            />
          </div>
          <div className="mbuttercup-pdpa-frame15135">
            <div className="mbuttercup-pdpa-frame15162">
              <span className="mbuttercup-pdpa-text">
                <span>Iris Reticulata</span>
              </span>
              <div className="mbuttercup-pdpa-frame15217">
                <button className="mbuttercup-pdpa-dbutton-dot">
                  <img
                    alt="IconSCaretI327"
                    src="/external/iconscareti327-y0u3.svg"
                    className="mbuttercup-pdpa-icon-scaret"
                  />
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="mbuttercup-pdpa-mprimary-nav">
          <div className="mbuttercup-pdpa-icon-hamburger">
            <img
              alt="HamburgerI327"
              src="/external/hamburgeri327-i0l.svg"
              className="mbuttercup-pdpa-hamburger"
            />
          </div>
          <img
            alt="LogoWordmarkI327"
            src="/external/logowordmarki327-6wnw.svg"
            className="mbuttercup-pdpa-logo-wordmark"
          />
          <div className="mbuttercup-pdpa-icon-basket">
            <img
              alt="UnionI327"
              src="/external/unioni327-mxg.svg"
              className="mbuttercup-pdpa-union"
            />
          </div>
        </div>
        <div className="mbuttercup-pdpa-frame15161">
          <div className="mbuttercup-pdpa-frame15218">
            <div className="mbuttercup-pdpa-mqty-stepper">
              <div className="mbuttercup-pdpa-qty-selector">
                <span className="mbuttercup-pdpa-text2 📱HandheldBodyLargeDefault">
                  1
                </span>
              </div>
              <div className="mbuttercup-pdpa-frame15160">
                <div className="mbuttercup-pdpa-qty-selector1">
                  <div className="mbuttercup-pdpa-icon-minus">
                    <img
                      alt="PlusI327"
                      src="/external/plusi327-9ix.svg"
                      className="mbuttercup-pdpa-plus"
                    />
                  </div>
                </div>
                <div className="mbuttercup-pdpa-qty-selector2">
                  <div className="mbuttercup-pdpa-icon-plus">
                    <img
                      alt="PlusI327"
                      src="/external/plusi327-qm3x.svg"
                      className="mbuttercup-pdpa-plus1"
                    />
                  </div>
                </div>
              </div>
            </div>
            <span className="mbuttercup-pdpa-text3 📱HandheldBodyLargeBold">
              <span>$1.99/ea</span>
            </span>
          </div>
          <button className="mbuttercup-pdpa-mbutton-pill">
            <span className="mbuttercup-pdpa-text5 📱HandheldBodyLargeDefault">
              <span>Add to basket</span>
            </span>
            <div className="mbuttercup-pdpa-icon-basket1">
              <img
                alt="UnionI327"
                src="/external/unioni327-h23l.svg"
                className="mbuttercup-pdpa-union1"
              />
            </div>
          </button>
        </div>
      </div>
    </div>
  )
}

export default MButtercupPDPA
